---
title: "NEON forecast challenge submission"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-packages, echo = F, warning=F, message=F}
## install.packages('remotes')
## install.packages('fpp3') # package for applying simple forecasting methods
## install.packages('tsibble') # package for dealing with time series data sets and tsibble objects
## install.packages('tidyverse') # collection of R packages for data manipulation, analysis, and visualisation
## install.packages('lubridate') # working with dates and times
## remotes::install_github('eco4cast/neon4cast') # package from NEON4cast challenge organisers to assist with forecast building and submission

# Load packages
library(tidyverse)
library(lubridate)
library(neon4cast)

```

```{r get-targets, message=F}
#read in the targets data
targets <- read_csv('https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz')

# read in the sites data
aquatic_sites <- read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-targets/main/NEON_Field_Site_Metadata_20220412.csv") |>
  dplyr::filter(aquatics == 1)

lake_sites <- aquatic_sites %>%
  filter(field_site_subtype == 'Lake')

# Filter the targets
targets <- targets %>%
  filter(site_id %in% lake_sites$field_site_id,
         variable == 'oxygen')
```

```{r get-NOAA-past, message = F}

# Past stacked weather
noaa_past_s3 <- neon4cast::noaa_stage3()

variables <- c("air_temperature", "relative_humidity")
#Other variable names can be found at https://projects.ecoforecast.org/neon4cast-docs/Shared-Forecast-Drivers.html#stage-3

noaa_past <- noaa_past_s3  |> 
  dplyr::filter(site_id %in% lake_sites$field_site_id,
                datetime >= ymd('2017-01-01'),
                variable %in% variables) |> 
  dplyr::collect()

# aggregate the past to mean values
noaa_past_mean <- noaa_past |> 
  mutate(datetime = as_date(datetime)) |> 
  group_by(datetime, site_id, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  pivot_wider(names_from = variable, values_from = prediction) |> 
  # convert air temp to C
  mutate(air_temperature = air_temperature - 273.15)

```

```{r get-NOAA-future, message = F}
# Future weather
# New forecast only available at 5am UTC the next day
forecast_date <- Sys.Date() 
noaa_date <- forecast_date - days(1)

noaa_future_s3 <- neon4cast::noaa_stage2(start_date = as.character(noaa_date))
variables <- c("air_temperature", "relative_humidity")

noaa_future <- noaa_future_s3 |> 
  dplyr::filter(datetime >= forecast_date,
                site_id %in% lake_sites$field_site_id,
                variable %in% variables) |> 
  collect()

noaa_future_daily <- noaa_future |> 
  mutate(datetime = as_date(datetime)) |> 
  # mean daily forecasts at each site per ensemble
  group_by(datetime, site_id, parameter, variable) |> 
  summarize(prediction = mean(prediction)) |>
  pivot_wider(names_from = variable, values_from = prediction) |>
  # convert to Celsius
  mutate(air_temperature = air_temperature - 273.15) |> 
  select(datetime, site_id, air_temperature, parameter, relative_humidity)
```

```{r model-setup}
# Generate a dataframe to fit the model to 
targets_lm <- targets |> 
  filter(variable == 'oxygen' ) |>
  pivot_wider(names_from = 'variable', values_from = 'observation') |> 
  left_join(noaa_past_mean, 
            by = c("datetime","site_id"))

```

```{r forecast-loop}
#set up forecast horizon for 7 days
forecast_horizon <- 7


forecast_dates <- seq(from = ymd(forecast_date), to = ymd(forecast_date) + forecast_horizon, by = "day")
n_members <- 31

# Loop through each site to fit the model, resets forecast
forecast_df <- NULL

#Loop through each site
for(i in 1:length(lake_sites$field_site_id)) {  
  
  #pull past data
  curr_site <- lake_sites$field_site_id[i]
  
  # Get only the necessary data for the specific site
  site_target <- targets_lm |>
    filter(site_id == curr_site) |>
    na.omit()

  noaa_future_site <- noaa_future_daily |> 
    filter(site_id == curr_site)
  
  #Fit linear model based on past data: oxygen = m * air temperature + + relative humidity + b
  fit <- lm(site_target$oxygen ~ site_target$air_temperature + site_target$relative_humidity)
  
  #adding parameter uncertainty
  fit_summary <- summary(fit) 
  
  coeffs <- round(fit$coefficients, 2)
  params_se <- fit_summary$coefficients[,2]
  
  mod <- predict(fit, data = site_target)

  residuals <- predict(fit, data =  site_target$oxygen)
  
  sigma <- sd(residuals, na.rm = TRUE)
  
  param_df <- data.frame(beta1 = rnorm(n_members, coeffs[1], params_se[1]),
                       beta2 = rnorm(n_members, coeffs[2], params_se[2]),
                       beta3 = rnorm(n_members, coeffs[3], params_se[3]))
  
  # Loop through all forecast dates
  for (t in 1:length(forecast_dates)) {
  
  #pull driver ensemble for the relevant date; here we are using all 30 NOAA ensemble members
  site_drivers <- noaa_future_site %>%
    filter(datetime == forecast_dates[t])
  
  # use linear regression to forecast water temperature for each ensemble member
  # The model here needs to match the model used in the lm function above (or what model you used in the fit)
  forecasted_oxygen <- param_df$beta1 + param_df$beta2 * site_drivers$air_temperature + site_drivers$relative_humidity * param_df$beta3 + rnorm(n = n_members, mean = 0, sd = sigma) 
    
  # put all the relevant information into a tibble that we can bind together
  curr_site_df <- tibble(datetime = rep(forecast_dates[t], times = n_members),
                         site_id = curr_site,
                         parameter = 1:n_members,
                         prediction = forecasted_oxygen,
                         variable = "oxygen") 
  
  forecast_df <- dplyr::bind_rows(forecast_df, curr_site_df)
  
  }
  
  message(curr_site, 'forecast run')
}
```

```{r make-standard}
# Make forecast fit the EFI standards
my_model_id <- 'example_LF_FirstForecast_wunc'

forecast_df_EFI <- forecast_df %>%
  filter(datetime > forecast_date) %>%
  mutate(model_id = my_model_id,
         reference_datetime = forecast_date,
         family = 'ensemble',
         parameter = as.character(parameter)) %>%
  select(datetime, reference_datetime, site_id, family, parameter, variable, prediction, model_id)

```

```{r write-forecast}
# Write the forecast to file
theme <- 'aquatics'
date <- forecast_df_EFI$reference_datetime[1]
forecast_name_1 <- paste0(forecast_df_EFI$model_id[1], ".csv")
forecast_file_1 <- paste(theme, date, forecast_name_1, sep = '-')
forecast_file_1


if (!dir.exists('Forecasts')) {
  dir.create('Forecasts')
}

write_csv(forecast_df_EFI, file.path('Forecasts',forecast_file_1))

```


```{r submit-forecast}

## # can uses the neon4cast::forecast_output_validator() to check the forecast is in the right format

# UNCOMMMENT THIS WHEN YOU ARE READY TO SUBMIT
## neon4cast::submit(forecast_file = file.path('Forecasts', forecast_file_1),
##                   ask = FALSE) # if ask = T (default), it will produce a pop-up box asking if you want to submit


```

```{r plot-forecast}
forecast_df_EFI |> 
  ggplot(aes(x=datetime, y=prediction, group = parameter)) +
  geom_line() +
  facet_wrap(~site_id) +
  labs(title = paste0('Forecast generated for ', forecast_df_EFI$variable[1], ' on ', forecast_df_EFI$reference_datetime[1]))
```